# Generated by Django 3.1.1 on 2020-11-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='organization_text',
            field=models.CharField(default=1, max_length=200000),
            preserve_default=False,
        ),
    ]
