# Generated by Django 3.1.1 on 2020-11-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_review_organization_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
    ]
