# Generated by Django 3.1.1 on 2020-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_remove_review_organization_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_organization',
            field=models.CharField(default=1, max_length=200000),
            preserve_default=False,
        ),
    ]
