# Generated by Django 3.1.1 on 2020-11-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_review_review_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.organization'),
        ),
    ]
